import { DOCTRINE } from "./doctrine";
import { MOVES_PER_CRANE_PER_TICK, ticksToHours, CONNECTION_AT_RISK_LEAD_TICKS } from "./config";
import { serviceById } from "./roster";
import { ticksUntilTideWindow } from "./tide";
import type { Berth, CargoLot, Customer, SimState, Vessel, VesselDataMode } from "./types";

// GR-1: every vessel field in this release is generated by the simulation. The
// function is the seam a live provider (GR-8, deferred) would widen — callers
// label their UI from this rather than hard-coding "simulated", so adding a
// provider later changes one function, not every panel.
export function vesselDataMode(_v: Vessel): VesselDataMode {
  return "fully_simulated";
}

export function yardBlockOccupiedTEU(state: SimState, blockId: string): number {
  // "outbound" lots are transshipment boxes claimed by an alongside vessel that
  // is loading them (REAL-2) — they still physically occupy the yard until lifted.
  return state.cargoLots
    .filter((l) => l.blockId === blockId && (l.status === "yard" || l.status === "discharging" || l.status === "outbound"))
    .reduce((s, l) => s + l.quantityTEU, 0);
}

export function yardBlockUtilisationPct(state: SimState, blockId: string): number {
  const block = state.yardBlocks.find((b) => b.id === blockId);
  if (!block) return 0;
  return (yardBlockOccupiedTEU(state, blockId) / block.capacityTEU) * 100;
}

export function yardUtilisationPct(state: SimState): number {
  const cap = state.yardBlocks.reduce((s, b) => s + b.capacityTEU, 0);
  const used = state.yardBlocks.reduce((s, b) => s + yardBlockOccupiedTEU(state, b.id), 0);
  return cap === 0 ? 0 : (used / cap) * 100;
}

export function craneAvailabilityPct(state: SimState): number {
  if (state.cranes.length === 0) return 100;
  const avail = state.cranes.reduce((s, c) => {
    // Weather-suspended cranes are operationally unavailable (D-54 — accepted
    // mild double-count with the score's 15% weather term).
    if (c.kind === "STS" && state.wxOps.stsSuspended) return s;
    if (c.kind === "RTG" && state.wxOps.rtgSuspended) return s;
    if (c.status === "operational") return s + 1;
    if (c.status === "degraded") return s + 0.5;
    return s;
  }, 0);
  return (avail / state.cranes.length) * 100;
}

// Effective crane units working a berth (degraded = half). Shared by the cargo
// tick stage and the D-55 wait projection.
export function craneUnitsAtBerth(state: SimState, berthId: string): number {
  const berth = state.berths.find((b) => b.id === berthId);
  if (!berth) return 0;
  return berth.craneIds.reduce((s, cid) => {
    const c = state.cranes.find((x) => x.id === cid);
    if (!c) return s;
    if (c.status === "operational") return s + 1;
    if (c.status === "degraded") return s + 0.5;
    return s;
  }, 0);
}

export function berthOccupancyPct(state: SimState): number {
  const usable = state.berths.filter((b) => b.status !== "closed").length;
  const occupied = state.berths.filter((b) => b.status === "occupied").length;
  return usable === 0 ? 0 : (occupied / usable) * 100;
}

export function vesselPriorityRank(v: Vessel): number {
  const hasHaz = v.manifest.some((m) => m.type === "hazmat");
  const hasReefer = v.manifest.some((m) => m.type === "reefer");
  if (hasHaz) return 0;
  if (hasReefer) return 1;
  return 2;
}

export function anchorageQueue(state: SimState): Vessel[] {
  return state.vessels
    .filter((v) => v.status === "anchored")
    .sort((a, b) => {
      const pr = vesselPriorityRank(a) - vesselPriorityRank(b);
      if (pr !== 0) return pr;
      const wa = a.anchoredSinceTick ?? 0;
      const wb = b.anchoredSinceTick ?? 0;
      if (wa !== wb) return wa - wb;
      return a.etaTick - b.etaTick;
    });
}

export function vesselWaitHours(state: SimState, v: Vessel): number {
  if (v.anchoredSinceTick === undefined) return 0;
  return ticksToHours(state.clock.tick - v.anchoredSinceTick);
}

// D-75: the worst waiter — averages hide the one vessel breaching doctrine.
export function maxAnchorageWait(state: SimState): { hours: number; vessel: Vessel } | null {
  const anchored = state.vessels.filter((v) => v.status === "anchored");
  if (anchored.length === 0) return null;
  let worst = anchored[0];
  for (const v of anchored) if (vesselWaitHours(state, v) > vesselWaitHours(state, worst)) worst = v;
  return { hours: Number(vesselWaitHours(state, worst).toFixed(1)), vessel: worst };
}

export function averageBerthWaitHours(state: SimState): number {
  const waiting = state.vessels.filter((v) => v.status === "anchored");
  if (waiting.length === 0) return 0;
  return waiting.reduce((s, v) => s + vesselWaitHours(state, v), 0) / waiting.length;
}

export function vesselsWaiting(state: SimState): number {
  return state.vessels.filter((v) => v.status === "anchored").length;
}

export function isHighPriority(state: SimState, customerId?: string): boolean {
  if (!customerId) return false;
  const c = state.customers.find((cu) => cu.id === customerId);
  return !!c && (c.defaultPriority === "high" || c.temperatureSensitive);
}

export function lotDwellDays(state: SimState, lot: CargoLot): number {
  if (lot.dwellStartTick === undefined) return 0;
  return ticksToHours(state.clock.tick - lot.dwellStartTick) / 24;
}

// Remaining ticks of the active storm disruption, if any — the deterministic
// horizon for weather-suspension estimates and hold-until times (D-55).
export function remainingStormTicks(state: SimState): number {
  const storm = state.disruptions.find(
    (d) => d.type === "storm" && state.clock.tick >= d.startTick && state.clock.tick < d.startTick + d.durationTicks,
  );
  return storm ? storm.startTick + storm.durationTicks - state.clock.tick : 0;
}

const DEPART_TICKS = 2; // unberthing manoeuvre after work completes

// D-70: ticks until a single berth is expected to free — the per-berth estimate
// inside the D-55 projection, extracted so the chatbot's berth-option block and
// the wait projection share one derivation. Work is frozen while STS cranes or
// vessel moves are weather-suspended: every estimate shifts by the storm's
// remaining ticks (or the staged recovery window when suspended under live
// weather with no scripted end).
export function berthFreeTicks(state: SimState, b: Berth): number {
  const suspended = state.wxOps.stsSuspended || state.wxOps.movesSuspended;
  const suspensionLag = suspended ? Math.max(remainingStormTicks(state), DOCTRINE.weather.recoveryClearTicks) : 0;
  // REAL-4 (D-82): the outgoing vessel's own unberthing needs the pilot/tug
  // pool too — if it's currently exhausted, add one tick of contention lag.
  const pilotageLag =
    state.pilotage.pilotsAvailable < 1 || state.pilotage.tugsAvailable < DOCTRINE.pilotage.tugsPerManoeuvre ? 1 : 0;
  if (b.status === "available") return suspensionLag + pilotageLag;
  const occupant = state.vessels.find((v) => v.id === b.vesselId);
  if (!occupant) return suspensionLag + pilotageLag;
  const total = occupant.manifest.reduce((s, m) => s + m.quantityTEU, 0);
  const rate = craneUnitsAtBerth(state, b.id) * MOVES_PER_CRANE_PER_TICK;
  const workTicks = rate > 0 ? Math.ceil(((1 - occupant.workProgress) * total) / rate) : 999;
  return workTicks + DEPART_TICKS + suspensionLag + pilotageLag;
}

// D-70: suitable berths for a vessel ranked by earliest expected availability
// (deep-water rule honoured, closed berths excluded, top 3). Pure and
// deterministic — provenance `calculated`.
export type BerthOption = { berthId: string; freesInHours: number };

export function berthOptions(state: SimState, vessel: Vessel): BerthOption[] {
  // REAL-5 (D-83): a neopanamax needs the tide window too, on top of whichever
  // deep-water berth frees up (OPS-TIDE §1).
  const tideLag = vessel.class === "neopanamax" ? ticksUntilTideWindow(state) : 0;
  return state.berths
    .filter((b) => b.status !== "closed" && (vessel.class !== "neopanamax" || b.deepWater))
    .map((b) => ({ berthId: b.id, freesInHours: Number(ticksToHours(berthFreeTicks(state, b) + tideLag).toFixed(1)) }))
    .sort((a, b) => a.freesInHours - b.freesInHours)
    .slice(0, 3);
}

// D-55: class-aware projected anchorage wait for a vessel, in hours. Estimates
// when each suitable berth frees (occupant's remaining TEU over its effective
// crane rate + a departing manoeuvre), adds the remaining weather-suspension
// ticks, then walks the doctrine-ordered queue ahead of this vessel. Pure and
// deterministic — provenance `calculated`.
export function projectedBerthWaitHours(state: SimState, vessel: Vessel): number {
  const suitable = state.berths.filter(
    (b) => b.status !== "closed" && (vessel.class !== "neopanamax" || b.deepWater),
  );
  if (suitable.length === 0) return 999;

  // REAL-5 (D-83): a neopanamax also needs the tide window (OPS-TIDE §1).
  const tideLag = vessel.class === "neopanamax" ? ticksUntilTideWindow(state) : 0;
  const freeTicks = suitable.map((b) => berthFreeTicks(state, b) + tideLag).sort((a, b) => a - b);

  // Vessels ahead in the doctrine order consume the earliest berths; an
  // approaching vessel queues behind everyone currently anchored.
  const queue = anchorageQueue(state);
  const pos = vessel.status === "anchored" ? Math.max(0, queue.indexOf(vessel)) : queue.length;

  let waitTicks: number;
  if (pos < freeTicks.length) {
    waitTicks = freeTicks[pos];
  } else {
    // Beyond the first round of berths, later queue slots wait an average
    // service duration per extra round — estimated from the queue's manifests.
    const rate = MOVES_PER_CRANE_PER_TICK * 2; // two STS per berth
    const totals = queue.map((v) => v.manifest.reduce((s, m) => s + m.quantityTEU, 0));
    const avgTotal = totals.length > 0 ? totals.reduce((a, b) => a + b, 0) / totals.length : rate * 12;
    const serviceTicks = Math.max(4, Math.ceil(avgTotal / rate) + DEPART_TICKS);
    const overflow = pos - freeTicks.length + 1;
    waitTicks = freeTicks[freeTicks.length - 1] + overflow * serviceTicks;
  }
  return Number(ticksToHours(waitTicks).toFixed(1));
}

// A vessel's cargo delay in days — same delayed predicate the KPI uses:
// diverted, or anchored beyond the high-priority delay threshold. Diverted
// vessels (no wait clock) count a minimum one day.
function vesselDelayDays(state: SimState, v: Vessel): number {
  return Number((vesselWaitHours(state, v) / 24).toFixed(1)) || 1;
}

function isDelayed(state: SimState, v: Vessel): boolean {
  return v.status === "diverted" || (v.status === "anchored" && vesselWaitHours(state, v) > DOCTRINE.cargo.highPriorityDelayHours);
}

// D-56: THE safety-stock quantity — one author, everywhere. Expected delay is
// the MAXIMUM across the customer's delayed vessels (owner ruling: cover must
// survive the worst shipment); shortfall = max(1, ceil(delay − cover)).
export function safetyStockShortfallDays(state: SimState, customerId: string): number {
  const customer = state.customers.find((c) => c.id === customerId);
  if (!customer) return 1;
  let expectedDelayDays = 0;
  for (const v of state.vessels) {
    if (!isDelayed(state, v)) continue;
    if (!v.manifest.some((m) => m.customerId === customerId)) continue;
    expectedDelayDays = Math.max(expectedDelayDays, vesselDelayDays(state, v));
  }
  return Math.max(1, Math.ceil(expectedDelayDays - customer.daysOfCoverRemaining));
}

// D-56 (5): the per-customer safety-stock picture — feeds the rule engine and
// the chatbot's structured [calculated] advisory block from one derivation.
export type SafetyStockOutlook = {
  customer: Customer;
  affectedTEU: number;
  expectedDelayDays: number;
  shortfallDays: number;
  pendingRec: boolean;
};

export function safetyStockOutlook(state: SimState): SafetyStockOutlook[] {
  const out: SafetyStockOutlook[] = [];
  for (const customer of state.customers) {
    if (!isHighPriority(state, customer.id)) continue;
    let affectedTEU = 0;
    let expectedDelayDays = 0;
    for (const v of state.vessels) {
      if (!isDelayed(state, v)) continue;
      const teu = v.manifest.filter((m) => m.customerId === customer.id).reduce((s, m) => s + m.quantityTEU, 0);
      if (teu === 0) continue;
      affectedTEU += teu;
      expectedDelayDays = Math.max(expectedDelayDays, vesselDelayDays(state, v));
    }
    if (affectedTEU === 0) continue;
    out.push({
      customer,
      affectedTEU,
      expectedDelayDays,
      shortfallDays: safetyStockShortfallDays(state, customer.id),
      pendingRec: state.recommendations.some(
        (r) => r.status === "pending" && r.proposedEffect.kind === "safetyStockAdvisory" && r.proposedEffect.customerId === customer.id,
      ),
    });
  }
  return out;
}

export function teuAtRisk(state: SimState): number {
  let total = 0;
  for (const v of state.vessels) {
    const delayed = v.status === "diverted" || (v.status === "anchored" && vesselWaitHours(state, v) > DOCTRINE.cargo.highPriorityDelayHours);
    if (!delayed) continue;
    for (const m of v.manifest) {
      if (isHighPriority(state, m.customerId)) total += m.quantityTEU;
    }
  }
  for (const lot of state.cargoLots) {
    if (lot.status !== "yard") continue;
    if (isHighPriority(state, lot.customerId) && lotDwellDays(state, lot) > DOCTRINE.cargo.dwellFlagDays) {
      total += lot.quantityTEU;
    }
  }
  return total;
}

// REAL-2 (D-80): transshipment connection state. A waiting box (status "yard"
// with an onward service) is "at risk" as its connection deadline nears without
// an onward vessel having lifted it; past the deadline it is "missed" and
// re-books to the next weekly call (tracked by connectMissedCount).
export function transshipmentWaiting(state: SimState): CargoLot[] {
  return state.cargoLots.filter((l) => l.status === "yard" && l.connectingServiceId !== undefined);
}

export function isConnectionAtRisk(state: SimState, lot: CargoLot): boolean {
  return (
    lot.status === "yard" &&
    lot.connectingServiceId !== undefined &&
    lot.connectDeadlineTick !== undefined &&
    lot.connectDeadlineTick - state.clock.tick <= CONNECTION_AT_RISK_LEAD_TICKS
  );
}

export function connectionsAtRisk(state: SimState): CargoLot[] {
  return transshipmentWaiting(state).filter((l) => isConnectionAtRisk(state, l));
}

export function connectionsAtRiskTEU(state: SimState): number {
  return connectionsAtRisk(state).reduce((s, l) => s + l.quantityTEU, 0);
}

export function connectionsMissed(state: SimState): CargoLot[] {
  return state.cargoLots.filter((l) => l.status === "yard" && (l.connectMissedCount ?? 0) >= 1);
}

// REAL-3 (D-81): real terminal-operator KPIs, derived from the rolling logs in
// state.terminal (per-vessel arrival/berth/departure stamps + per-tick moves).

// % of recent completed calls that berthed with no anchor wait. No history yet → 100.
export function berthOnArrivalPct(state: SimState): number {
  const c = state.terminal.completions;
  if (c.length === 0) return 100;
  return Math.round((c.filter((x) => x.berthOnArrival).length / c.length) * 100);
}

// Average vessel turnaround (arrival → departure) over recent calls, in hours.
export function avgTurnaroundHours(state: SimState): number {
  const c = state.terminal.completions;
  if (c.length === 0) return 0;
  const avgTicks = c.reduce((s, x) => s + x.turnaroundTicks, 0) / c.length;
  return Number(ticksToHours(avgTicks).toFixed(1));
}

// Gross moves per WORKING STS crane per hour over the move window (GCR). Runs on
// the compressed clock, so the value is high — see the calibration record.
export function craneMovesPerHour(state: SimState): number {
  const m = state.terminal.moves;
  const productive = m.reduce((s, x) => s + x.productive, 0);
  const craneTicks = m.reduce((s, x) => s + x.craneTicks, 0);
  if (craneTicks === 0) return 0;
  return Math.round(productive / ticksToHours(craneTicks));
}

// % of yard moves that were unproductive rehandles over the move window.
export function rehandleRatio(state: SimState): number {
  const m = state.terminal.moves;
  const productive = m.reduce((s, x) => s + x.productive, 0);
  const rehandle = m.reduce((s, x) => s + x.rehandle, 0);
  const total = productive + rehandle;
  if (total === 0) return 0;
  return Math.round((rehandle / total) * 100);
}

export type ConnectionRisk = { serviceId: string; serviceName: string; teu: number; count: number; earliestDeadline: number };

// At-risk connections grouped by onward service, soonest deadline first — feeds
// the at-risk alert text and the connection-protection rule (which onward vessel
// to prioritise).
export function atRiskByService(state: SimState): ConnectionRisk[] {
  const groups = new Map<string, { teu: number; count: number; earliestDeadline: number }>();
  for (const l of connectionsAtRisk(state)) {
    const sid = l.connectingServiceId!;
    const g = groups.get(sid) ?? { teu: 0, count: 0, earliestDeadline: Infinity };
    g.teu += l.quantityTEU;
    g.count += 1;
    g.earliestDeadline = Math.min(g.earliestDeadline, l.connectDeadlineTick ?? Infinity);
    groups.set(sid, g);
  }
  return [...groups.entries()]
    .map(([serviceId, g]) => ({ serviceId, serviceName: serviceById(serviceId)?.name ?? serviceId, ...g }))
    .sort((a, b) => a.earliestDeadline - b.earliestDeadline);
}
